version: 2.1

orbs: # Orbs
  aws-ecr: circleci/aws-ecr@8.1.2
  github-cli: circleci/github-cli@2.0.0
  node: circleci/node@5.0.2

jobs:
  build_push_ecr:
    machine:
      docker_layer_caching: true # Docker Layer Caching
      resource_class: large
      image: ubuntu-2004:current
    steps:
      - checkout
      - aws-ecr/build-and-push-image: # AWS ECR Orb
          assume-web-identity: true
          role-arn: arn:aws:iam::660990364978:role/tadashi_oidc_fargate
          repo: tadashi-eks-argocd-demo
          tag: '${CIRCLE_SHA1}'

workflows:
  test_and_deploy: 
    jobs:
      - node/run:
          name: lint
          npm-run: lint
      - node/run:
          name: build
          npm-run: build
      - build_push_ecr:
          context: aws-oidc-fargate
          filters:
            branches:
              only: master
