#Comment to trigger commit
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3
  github-cli: circleci/github-cli@2.0.0
  node: circleci/node@5.0.2

jobs:
  build_push_ecr:
    machine:
      docker_layer_caching: true
      resource_class: large
      image: ubuntu-2004:current
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          region: ${AWS_DEFAULT_REGION}
          tag: "${CIRCLE_SHA1}"
          registry-id: AWS_ECR_REGISTRY_ID


  create_release_pr:
    docker:
      - image: cimg/base:2022.06
    steps:
      - github-cli/setup
      - github-cli/clone:
          repo: git@github.com:tadashi0713/circleci-demo-eks-argocd-manifest.git
      - run:
          name: Change image tag
          working_directory: base
          command: |
            ./kustomize edit set image circleci-demo-eks-argocd-app=${ECR_REPO}:${CIRCLE_SHA1:0:7}
      - add_ssh_keys:
          fingerprints:
            - $SSH_KEY_FINGERPRINT
      - run:
          name: Commit file
          command: |
            git config --global user.email "gitops@example.com"
            git config --global user.name "GitOps Bot"
            git remote set-url --push origin git@github.com:brianoh1979/circleci-demo-eks-argocd-manifest.git
            git checkout -b release-${CIRCLE_SHA1:0:7}
            git add .
            git commit -m"Release circleci-demo-eks-argocd-app ${CIRCLE_SHA1:0:7}"
            git push origin HEAD
      - run: sleep 10
      - run:
          name: Create Pull Request
          command: gh pr create --fill --base=master -t "Release circleci-demo-eks-argocd-app ${CIRCLE_SHA1:0:7}" -b ""

workflows:
  test_and_deploy: 
    jobs:
      - node/run:
          name: lint
          npm-run: lint
      - node/run:
          name: build
          npm-run: build
      - build_push_ecr:
          filters:
            branches:
              only: master
      - create_release_pr:
          requires:
            - build_push_ecr
