version: 2.1

orbs: # Orbs
  aws-ecr: circleci/aws-ecr@8.1.2
  github-cli: circleci/github-cli@2.0.0
  node: circleci/node@5.0.2

workflows:
  test_and_deploy: 
    jobs:
      - node/run:
          name: lint
          npm-run: lint
      - node/run:
          name: build
          npm-run: build
      - aws-ecr/build-and-push-image:
          assume-web-identity: true
          role-arn: arn:aws:iam::660990364978:role/tadashi_oidc_fargate
          platform: linux/amd64
          repo: tadashi-graviton-fargate-demo
          tag: '${CIRCLE_SHA1}'
          context:
            - aws-oidc-fargate
