version: 2.1

orbs: # Orbs
  aws-ecr: circleci/aws-ecr@8.1.2
  github-cli: circleci/github-cli@2.0.0
  node: circleci/node@5.0.2

jobs:
  build_push_ecr:
    machine:
      docker_layer_caching: true # Docker Layer Caching
      resource_class: large
      image: ubuntu-2004:current
    steps:
      - checkout
      - aws-ecr/build-and-push-image: # AWS ECR Orb
          assume-web-identity: true
          role-arn: arn:aws:iam::660990364978:role/tadashi_oidc_fargate
          repo: tadashi-eks-argocd-demo
          tag: '${CIRCLE_SHA1}'

  create_release_pr:
    docker:
      - image: cimg/deploy:2022.06.1
    steps:
      - github-cli/setup
      - github-cli/clone:
          repo: git@github.com:tadashi0713/circleci-demo-eks-argocd-manifest.git
      - run:
          name: Change image tag
          working_directory: base
          command: kustomize edit set image circleci-demo-eks-argocd-app=660990364978.dkr.ecr.ap-northeast-1.amazonaws.com/tadashi-eks-argocd-demo:${CIRCLE_SHA1}

workflows:
  test_and_deploy: 
    jobs:
      - node/run:
          name: lint
          npm-run: lint
      - node/run:
          name: build
          npm-run: build
      - build_push_ecr:
          context: aws-oidc-fargate
          filters:
            branches:
              only: master
      - create_release_pr:
          requires:
            - build_push_ecr
